version: '3.8'

services:
  supabase-mcp:
    build: .
    image: supabase-mcp-server:latest
    container_name: supabase-mcp-server
    environment:
      - NODE_ENV=production
      - SUPABASE_ACCESS_TOKEN=${SUPABASE_ACCESS_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - PROJECT_REF=${PROJECT_REF}
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true  # Keep STDIN open for MCP stdio communication
    tty: true         # Allocate a pseudo-TTY
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  mcp-network:
    driver: bridge

# Optional: Add a volume for logs if needed
# volumes:
#   mcp-logs:
#     driver: local